name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Prevent Out of Memory (OOM) Errors
      run: |
        # Only build for arm64 to save RAM and cut build time in half
        sed -i 's/arm64-v8a, armeabi-v7a/arm64-v8a/' buildozer.spec

    - name: Build with Official Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FastTransfer-APK
        path: ${{ steps.buildozer.outputs.filename }}
